$('#btn_start').click(function(){
	$("#message")
		.html("Message")
		.css("background-color","Red")
		.parent()
		.css("background-color","fff4dd")
		.width(150)
		.height(80)	
});
$('#btn_reset').click(function(){
	location.reload();
});